#*****************************************************************************
#App Configuration
#*****************************************************************************
application.title=EcosystemCore
application.version=0.0.12-SNAPSHOT

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
spring.main.allow-circular-references=true
