#*****************************************************************************
#App Configuration
#*****************************************************************************
application.title=EcosystemCore
application.version=0.0.14-SNAPSHOT
